/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as acordTaxonomyBackfillBatches from "../acordTaxonomyBackfillBatches.js";
import type * as actions_agentResponseFeedback from "../actions/agentResponseFeedback.js";
import type * as actions_archiveNonCoverageRequirements from "../actions/archiveNonCoverageRequirements.js";
import type * as actions_backfillAcordTaxonomy from "../actions/backfillAcordTaxonomy.js";
import type * as actions_backfillCarrierIdentity from "../actions/backfillCarrierIdentity.js";
import type * as actions_backfillChunks from "../actions/backfillChunks.js";
import type * as actions_backfillComplianceRequirementShape from "../actions/backfillComplianceRequirementShape.js";
import type * as actions_backfillLinesOfBusiness from "../actions/backfillLinesOfBusiness.js";
import type * as actions_cleanupLegacyLineOfBusinessFields from "../actions/cleanupLegacyLineOfBusinessFields.js";
import type * as actions_clientFileNaming from "../actions/clientFileNaming.js";
import type * as actions_compactThreadHistory from "../actions/compactThreadHistory.js";
import type * as actions_companyInformationExtraction from "../actions/companyInformationExtraction.js";
import type * as actions_complianceRequirements from "../actions/complianceRequirements.js";
import type * as actions_complianceReview from "../actions/complianceReview.js";
import type * as actions_connectedEmail from "../actions/connectedEmail.js";
import type * as actions_connectedEmailScan from "../actions/connectedEmailScan.js";
import type * as actions_createOutboundImessageGroup from "../actions/createOutboundImessageGroup.js";
import type * as actions_emailDraftReview from "../actions/emailDraftReview.js";
import type * as actions_emailDrafts from "../actions/emailDrafts.js";
import type * as actions_enrichCarrierIdentity from "../actions/enrichCarrierIdentity.js";
import type * as actions_extractCompanyInfo from "../actions/extractCompanyInfo.js";
import type * as actions_extractFromUpload from "../actions/extractFromUpload.js";
import type * as actions_extractSupplementary from "../actions/extractSupplementary.js";
import type * as actions_extractionIntegrityAudit from "../actions/extractionIntegrityAudit.js";
import type * as actions_extractionReviews from "../actions/extractionReviews.js";
import type * as actions_generateCoi from "../actions/generateCoi.js";
import type * as actions_handleInboundEmail from "../actions/handleInboundEmail.js";
import type * as actions_handleInboundImessage from "../actions/handleInboundImessage.js";
import type * as actions_handleInboundOperatorImessage from "../actions/handleInboundOperatorImessage.js";
import type * as actions_handleInboundSlack from "../actions/handleInboundSlack.js";
import type * as actions_mailboxCoordinator from "../actions/mailboxCoordinator.js";
import type * as actions_mcpChat from "../actions/mcpChat.js";
import type * as actions_mirrorWebChatToImessage from "../actions/mirrorWebChatToImessage.js";
import type * as actions_operatorAgentRichTools from "../actions/operatorAgentRichTools.js";
import type * as actions_ownComplianceMonitor from "../actions/ownComplianceMonitor.js";
import type * as actions_policyExtraction from "../actions/policyExtraction.js";
import type * as actions_processThreadChat from "../actions/processThreadChat.js";
import type * as actions_procurementIntake from "../actions/procurementIntake.js";
import type * as actions_procurementPacketUpdate from "../actions/procurementPacketUpdate.js";
import type * as actions_proposalExtraction from "../actions/proposalExtraction.js";
import type * as actions_proposalReview from "../actions/proposalReview.js";
import type * as actions_publicDemoAgent from "../actions/publicDemoAgent.js";
import type * as actions_reExtractFromFile from "../actions/reExtractFromFile.js";
import type * as actions_rechunkPolicy from "../actions/rechunkPolicy.js";
import type * as actions_reconcilePolicy from "../actions/reconcilePolicy.js";
import type * as actions_renderEmailPreview from "../actions/renderEmailPreview.js";
import type * as actions_retryExtraction from "../actions/retryExtraction.js";
import type * as actions_sendCertificateWorkflowJob from "../actions/sendCertificateWorkflowJob.js";
import type * as actions_sendIntroImessage from "../actions/sendIntroImessage.js";
import type * as actions_sendNotificationEmail from "../actions/sendNotificationEmail.js";
import type * as actions_sendNotificationImessage from "../actions/sendNotificationImessage.js";
import type * as actions_sendNotificationSlack from "../actions/sendNotificationSlack.js";
import type * as actions_sendOperatorSlack from "../actions/sendOperatorSlack.js";
import type * as actions_sendPendingEmail from "../actions/sendPendingEmail.js";
import type * as actions_sendSlack from "../actions/sendSlack.js";
import type * as actions_slackCredentials from "../actions/slackCredentials.js";
import type * as actions_slackOAuth from "../actions/slackOAuth.js";
import type * as actions_slackPresentation from "../actions/slackPresentation.js";
import type * as actions_slackReconciliation from "../actions/slackReconciliation.js";
import type * as actions_threadTitle from "../actions/threadTitle.js";
import type * as actions_updateDocumentChunk from "../actions/updateDocumentChunk.js";
import type * as actions_vendorComplianceMonitor from "../actions/vendorComplianceMonitor.js";
import type * as agentChannels from "../agentChannels.js";
import type * as agentHistory from "../agentHistory.js";
import type * as agentResponseFeedback from "../agentResponseFeedback.js";
import type * as agentTargets from "../agentTargets.js";
import type * as appCardLinks from "../appCardLinks.js";
import type * as auth from "../auth.js";
import type * as backfillDeclarationFacts from "../backfillDeclarationFacts.js";
import type * as backfillLinesOfBusinessBatches from "../backfillLinesOfBusinessBatches.js";
import type * as brokerProfiles from "../brokerProfiles.js";
import type * as carrierIdentityBackfill from "../carrierIdentityBackfill.js";
import type * as carrierIdentityCache from "../carrierIdentityCache.js";
import type * as certificateHolders from "../certificateHolders.js";
import type * as certificateLifecycle from "../certificateLifecycle.js";
import type * as certificateWorkflowJobs from "../certificateWorkflowJobs.js";
import type * as certificateWorkflowSettings from "../certificateWorkflowSettings.js";
import type * as certificates from "../certificates.js";
import type * as clRouterOperations from "../clRouterOperations.js";
import type * as cleanupLegacyLineOfBusinessFieldsBatches from "../cleanupLegacyLineOfBusinessFieldsBatches.js";
import type * as clientFiles from "../clientFiles.js";
import type * as clientProcurementRequests from "../clientProcurementRequests.js";
import type * as companyInformation from "../companyInformation.js";
import type * as compliance from "../compliance.js";
import type * as connectedEmail from "../connectedEmail.js";
import type * as connectedEmailAutomation from "../connectedEmailAutomation.js";
import type * as connectedOrgs from "../connectedOrgs.js";
import type * as conversationTurns from "../conversationTurns.js";
import type * as crons from "../crons.js";
import type * as declarationFacts from "../declarationFacts.js";
import type * as devClear from "../devClear.js";
import type * as documentChunks from "../documentChunks.js";
import type * as emailDeliveryAttempts from "../emailDeliveryAttempts.js";
import type * as emailDraftReviewLinks from "../emailDraftReviewLinks.js";
import type * as externalExtractionPayload from "../externalExtractionPayload.js";
import type * as extractionIntegrityAudit from "../extractionIntegrityAudit.js";
import type * as extractionReviews from "../extractionReviews.js";
import type * as extractionTraces from "../extractionTraces.js";
import type * as http from "../http.js";
import type * as imessageChats from "../imessageChats.js";
import type * as imessageInboundEvents from "../imessageInboundEvents.js";
import type * as imessageOutboundGroups from "../imessageOutboundGroups.js";
import type * as imessageOutboundSends from "../imessageOutboundSends.js";
import type * as imessagePrivacy from "../imessagePrivacy.js";
import type * as lib_access from "../lib/access.js";
import type * as lib_acordForms_select from "../lib/acordForms/select.js";
import type * as lib_acordForms_types from "../lib/acordForms/types.js";
import type * as lib_acordTaxonomyBackfill from "../lib/acordTaxonomyBackfill.js";
import type * as lib_acordTaxonomyBackfillReport from "../lib/acordTaxonomyBackfillReport.js";
import type * as lib_actionConfirmationFingerprint from "../lib/actionConfirmationFingerprint.js";
import type * as lib_actionFailures from "../lib/actionFailures.js";
import type * as lib_actorRef from "../lib/actorRef.js";
import type * as lib_agentAttachmentContext from "../lib/agentAttachmentContext.js";
import type * as lib_agentAttachmentLimits from "../lib/agentAttachmentLimits.js";
import type * as lib_agentHistoryLoader from "../lib/agentHistoryLoader.js";
import type * as lib_agentMessageHistory from "../lib/agentMessageHistory.js";
import type * as lib_agentPolicyFocus from "../lib/agentPolicyFocus.js";
import type * as lib_agentPolicyPresentation from "../lib/agentPolicyPresentation.js";
import type * as lib_agentPrompts from "../lib/agentPrompts.js";
import type * as lib_agentScope from "../lib/agentScope.js";
import type * as lib_agentSteps from "../lib/agentSteps.js";
import type * as lib_agentThreadAttachment from "../lib/agentThreadAttachment.js";
import type * as lib_agentToolAudit from "../lib/agentToolAudit.js";
import type * as lib_agentToolExecutors from "../lib/agentToolExecutors.js";
import type * as lib_aiClassifier from "../lib/aiClassifier.js";
import type * as lib_aiUtils from "../lib/aiUtils.js";
import type * as lib_apiAuth from "../lib/apiAuth.js";
import type * as lib_apiDto from "../lib/apiDto.js";
import type * as lib_apiError from "../lib/apiError.js";
import type * as lib_brandIcon from "../lib/brandIcon.js";
import type * as lib_branding from "../lib/branding.js";
import type * as lib_carrierIdentity from "../lib/carrierIdentity.js";
import type * as lib_carrierIdentityBackfill from "../lib/carrierIdentityBackfill.js";
import type * as lib_carrierIdentityEnrichment from "../lib/carrierIdentityEnrichment.js";
import type * as lib_carrierIdentityProjection from "../lib/carrierIdentityProjection.js";
import type * as lib_carrierIdentitySource from "../lib/carrierIdentitySource.js";
import type * as lib_certificateBrokerEmail from "../lib/certificateBrokerEmail.js";
import type * as lib_certificateDescription from "../lib/certificateDescription.js";
import type * as lib_certificateEndorsements from "../lib/certificateEndorsements.js";
import type * as lib_certificateHolderPopulation from "../lib/certificateHolderPopulation.js";
import type * as lib_certificateHolderResolution from "../lib/certificateHolderResolution.js";
import type * as lib_certificateIdentity from "../lib/certificateIdentity.js";
import type * as lib_certificateRequestGate from "../lib/certificateRequestGate.js";
import type * as lib_certificateRequirementPlan from "../lib/certificateRequirementPlan.js";
import type * as lib_channelAgentRunner from "../lib/channelAgentRunner.js";
import type * as lib_chatTools from "../lib/chatTools.js";
import type * as lib_clRouterClient from "../lib/clRouterClient.js";
import type * as lib_clRouterLanguageModel from "../lib/clRouterLanguageModel.js";
import type * as lib_clientFileNames from "../lib/clientFileNames.js";
import type * as lib_clientFiles from "../lib/clientFiles.js";
import type * as lib_coiAttachmentGuards from "../lib/coiAttachmentGuards.js";
import type * as lib_coiGenerator from "../lib/coiGenerator.js";
import type * as lib_companyInformationExtraction from "../lib/companyInformationExtraction.js";
import type * as lib_complianceAgent from "../lib/complianceAgent.js";
import type * as lib_complianceCheck from "../lib/complianceCheck.js";
import type * as lib_complianceRequirementMigration from "../lib/complianceRequirementMigration.js";
import type * as lib_complianceTypes from "../lib/complianceTypes.js";
import type * as lib_confidence from "../lib/confidence.js";
import type * as lib_coverageBreakdown from "../lib/coverageBreakdown.js";
import type * as lib_coverageNames from "../lib/coverageNames.js";
import type * as lib_coverageScoping from "../lib/coverageScoping.js";
import type * as lib_declarationFacts from "../lib/declarationFacts.js";
import type * as lib_deletePolicyRowsInBatches from "../lib/deletePolicyRowsInBatches.js";
import type * as lib_documentMapping from "../lib/documentMapping.js";
import type * as lib_domains from "../lib/domains.js";
import type * as lib_emailAddress from "../lib/emailAddress.js";
import type * as lib_emailCancelIntent from "../lib/emailCancelIntent.js";
import type * as lib_emailChange from "../lib/emailChange.js";
import type * as lib_emailCommandExecutor from "../lib/emailCommandExecutor.js";
import type * as lib_emailDelivery from "../lib/emailDelivery.js";
import type * as lib_emailDraftArtifacts from "../lib/emailDraftArtifacts.js";
import type * as lib_emailDraftService from "../lib/emailDraftService.js";
import type * as lib_emailDraftSummary from "../lib/emailDraftSummary.js";
import type * as lib_emailIdentity from "../lib/emailIdentity.js";
import type * as lib_emailPayloadFields from "../lib/emailPayloadFields.js";
import type * as lib_emailPolicySources from "../lib/emailPolicySources.js";
import type * as lib_emailSendIntent from "../lib/emailSendIntent.js";
import type * as lib_emailSubagent from "../lib/emailSubagent.js";
import type * as lib_emailTemplate from "../lib/emailTemplate.js";
import type * as lib_emailWorkflow from "../lib/emailWorkflow.js";
import type * as lib_entityTypes from "../lib/entityTypes.js";
import type * as lib_extraction from "../lib/extraction.js";
import type * as lib_extractionFieldReview from "../lib/extractionFieldReview.js";
import type * as lib_extractionIntegrityAudit from "../lib/extractionIntegrityAudit.js";
import type * as lib_extractionPostProcess from "../lib/extractionPostProcess.js";
import type * as lib_extractionPromotion from "../lib/extractionPromotion.js";
import type * as lib_extractionPromptGuidance from "../lib/extractionPromptGuidance.js";
import type * as lib_extractionTraceRouterFields from "../lib/extractionTraceRouterFields.js";
import type * as lib_featureFlags from "../lib/featureFlags.js";
import type * as lib_fireworksStructuredOutput from "../lib/fireworksStructuredOutput.js";
import type * as lib_forwardReplyDirection from "../lib/forwardReplyDirection.js";
import type * as lib_imapDestination from "../lib/imapDestination.js";
import type * as lib_imapMailbox from "../lib/imapMailbox.js";
import type * as lib_imessageAgentContext from "../lib/imessageAgentContext.js";
import type * as lib_imessageAgentRunState from "../lib/imessageAgentRunState.js";
import type * as lib_imessageAppCards from "../lib/imessageAppCards.js";
import type * as lib_imessageConfig from "../lib/imessageConfig.js";
import type * as lib_imessageDeterministicControls from "../lib/imessageDeterministicControls.js";
import type * as lib_imessageGroupResolution from "../lib/imessageGroupResolution.js";
import type * as lib_imessageIngress from "../lib/imessageIngress.js";
import type * as lib_imessageOutbound from "../lib/imessageOutbound.js";
import type * as lib_imessageSlashCommands from "../lib/imessageSlashCommands.js";
import type * as lib_inboundEmailDeterministicControls from "../lib/inboundEmailDeterministicControls.js";
import type * as lib_inboundEmailParser from "../lib/inboundEmailParser.js";
import type * as lib_industries from "../lib/industries.js";
import type * as lib_linesOfBusiness from "../lib/linesOfBusiness.js";
import type * as lib_liteparsePreprocessor from "../lib/liteparsePreprocessor.js";
import type * as lib_localSeedData from "../lib/localSeedData.js";
import type * as lib_magicLinkTokens from "../lib/magicLinkTokens.js";
import type * as lib_mailboxAutomation from "../lib/mailboxAutomation.js";
import type * as lib_mapboxAddress from "../lib/mapboxAddress.js";
import type * as lib_mcpAgentToolAccess from "../lib/mcpAgentToolAccess.js";
import type * as lib_mcpProtocol from "../lib/mcpProtocol.js";
import type * as lib_mergePdfs from "../lib/mergePdfs.js";
import type * as lib_modelCatalog from "../lib/modelCatalog.js";
import type * as lib_models from "../lib/models.js";
import type * as lib_notificationEmailTemplate from "../lib/notificationEmailTemplate.js";
import type * as lib_notificationThreadContext from "../lib/notificationThreadContext.js";
import type * as lib_notificationTypes from "../lib/notificationTypes.js";
import type * as lib_notify from "../lib/notify.js";
import type * as lib_operatorAgentChannel from "../lib/operatorAgentChannel.js";
import type * as lib_operatorAgentConfirmationPreflight from "../lib/operatorAgentConfirmationPreflight.js";
import type * as lib_operatorAgentContinuation from "../lib/operatorAgentContinuation.js";
import type * as lib_operatorAgentIntentRegistry from "../lib/operatorAgentIntentRegistry.js";
import type * as lib_operatorAgentToolRegistry from "../lib/operatorAgentToolRegistry.js";
import type * as lib_operatorIdentity from "../lib/operatorIdentity.js";
import type * as lib_operatorMcpAttachments from "../lib/operatorMcpAttachments.js";
import type * as lib_operatorMcpToolCatalog from "../lib/operatorMcpToolCatalog.js";
import type * as lib_operatorSlackConfig from "../lib/operatorSlackConfig.js";
import type * as lib_orgBranding from "../lib/orgBranding.js";
import type * as lib_orgProfileFacts from "../lib/orgProfileFacts.js";
import type * as lib_orgWiki from "../lib/orgWiki.js";
import type * as lib_orgWikiExtraction from "../lib/orgWikiExtraction.js";
import type * as lib_orgWikiPolicy from "../lib/orgWikiPolicy.js";
import type * as lib_pdfFiller from "../lib/pdfFiller.js";
import type * as lib_pdfSourceSpans from "../lib/pdfSourceSpans.js";
import type * as lib_pipelineMutations from "../lib/pipelineMutations.js";
import type * as lib_policyDocumentGate from "../lib/policyDocumentGate.js";
import type * as lib_policyDocumentStructure from "../lib/policyDocumentStructure.js";
import type * as lib_policyLookup from "../lib/policyLookup.js";
import type * as lib_policyPartyContext from "../lib/policyPartyContext.js";
import type * as lib_policyPeriodExtraction from "../lib/policyPeriodExtraction.js";
import type * as lib_policyProductIdentity from "../lib/policyProductIdentity.js";
import type * as lib_policyToolResolution from "../lib/policyToolResolution.js";
import type * as lib_policyTypes from "../lib/policyTypes.js";
import type * as lib_policyVersioning from "../lib/policyVersioning.js";
import type * as lib_procurement from "../lib/procurement.js";
import type * as lib_procurementCapabilities from "../lib/procurementCapabilities.js";
import type * as lib_procurementIntake from "../lib/procurementIntake.js";
import type * as lib_procurementNarrative from "../lib/procurementNarrative.js";
import type * as lib_procurementPacket from "../lib/procurementPacket.js";
import type * as lib_procurementRequirements from "../lib/procurementRequirements.js";
import type * as lib_proposalMarkdown from "../lib/proposalMarkdown.js";
import type * as lib_proposalReview from "../lib/proposalReview.js";
import type * as lib_publicDemoAgent from "../lib/publicDemoAgent.js";
import type * as lib_quoWebhook from "../lib/quoWebhook.js";
import type * as lib_requirementAttachmentIntent from "../lib/requirementAttachmentIntent.js";
import type * as lib_resend from "../lib/resend.js";
import type * as lib_sdkCallbacks from "../lib/sdkCallbacks.js";
import type * as lib_searchTokenizer from "../lib/searchTokenizer.js";
import type * as lib_security from "../lib/security.js";
import type * as lib_slackAvailability from "../lib/slackAvailability.js";
import type * as lib_slackBlocks from "../lib/slackBlocks.js";
import type * as lib_slackChannelRouting from "../lib/slackChannelRouting.js";
import type * as lib_slackConfig from "../lib/slackConfig.js";
import type * as lib_slackCredentials from "../lib/slackCredentials.js";
import type * as lib_slackInteractions from "../lib/slackInteractions.js";
import type * as lib_slackOAuthPolicy from "../lib/slackOAuthPolicy.js";
import type * as lib_slackPayload from "../lib/slackPayload.js";
import type * as lib_slackRetry from "../lib/slackRetry.js";
import type * as lib_slackSecurity from "../lib/slackSecurity.js";
import type * as lib_slackThreadContext from "../lib/slackThreadContext.js";
import type * as lib_slackThreadTitle from "../lib/slackThreadTitle.js";
import type * as lib_sourceTree from "../lib/sourceTree.js";
import type * as lib_spreadsheetText from "../lib/spreadsheetText.js";
import type * as lib_storedAgentFile from "../lib/storedAgentFile.js";
import type * as lib_taskControlIntent from "../lib/taskControlIntent.js";
import type * as lib_textChannelCommands from "../lib/textChannelCommands.js";
import type * as lib_textChannelControls from "../lib/textChannelControls.js";
import type * as lib_threadAccess from "../lib/threadAccess.js";
import type * as lib_threadActionConfirmationValidators from "../lib/threadActionConfirmationValidators.js";
import type * as lib_threadMessageValidators from "../lib/threadMessageValidators.js";
import type * as lib_transportRenderers from "../lib/transportRenderers.js";
import type * as lib_userFacingErrors from "../lib/userFacingErrors.js";
import type * as lib_userPhone from "../lib/userPhone.js";
import type * as lib_valueNormalization from "../lib/valueNormalization.js";
import type * as lib_vendorComplianceTools from "../lib/vendorComplianceTools.js";
import type * as lib_webChatDeterministicControls from "../lib/webChatDeterministicControls.js";
import type * as lib_webRetrieval from "../lib/webRetrieval.js";
import type * as lib_websiteBrand from "../lib/websiteBrand.js";
import type * as lib_workflows_certificateRequest from "../lib/workflows/certificateRequest.js";
import type * as lib_workflows_comms from "../lib/workflows/comms.js";
import type * as lib_workflows_index from "../lib/workflows/index.js";
import type * as lib_workflows_mailboxTasks from "../lib/workflows/mailboxTasks.js";
import type * as lib_workflows_types from "../lib/workflows/types.js";
import type * as memoryMaintenance from "../memoryMaintenance.js";
import type * as migrations from "../migrations.js";
import type * as modelConfig from "../modelConfig.js";
import type * as modelRoutingEvents from "../modelRoutingEvents.js";
import type * as modelSettings from "../modelSettings.js";
import type * as notificationPreferences from "../notificationPreferences.js";
import type * as notificationSlack from "../notificationSlack.js";
import type * as notifications from "../notifications.js";
import type * as oauth from "../oauth.js";
import type * as operator from "../operator.js";
import type * as operatorAgent from "../operatorAgent.js";
import type * as operatorAgentRunner from "../operatorAgentRunner.js";
import type * as operatorImessage from "../operatorImessage.js";
import type * as operatorProvisioning from "../operatorProvisioning.js";
import type * as operatorSlack from "../operatorSlack.js";
import type * as orgWiki from "../orgWiki.js";
import type * as organizations from "../organizations.js";
import type * as orgs from "../orgs.js";
import type * as pendingEmails from "../pendingEmails.js";
import type * as policies from "../policies.js";
import type * as policyAuditLog from "../policyAuditLog.js";
import type * as policyFiles from "../policyFiles.js";
import type * as policyVersions from "../policyVersions.js";
import type * as presence from "../presence.js";
import type * as procurementMigration from "../procurementMigration.js";
import type * as procurementPacket from "../procurementPacket.js";
import type * as procurementProposals from "../procurementProposals.js";
import type * as procurementRequests from "../procurementRequests.js";
import type * as procurementRequirements from "../procurementRequirements.js";
import type * as procurementSms from "../procurementSms.js";
import type * as proposalExtraction from "../proposalExtraction.js";
import type * as proposalSourceNodes from "../proposalSourceNodes.js";
import type * as proposalSourceSpans from "../proposalSourceSpans.js";
import type * as publicDemo from "../publicDemo.js";
import type * as quoBrokerWebhook from "../quoBrokerWebhook.js";
import type * as rateLimits from "../rateLimits.js";
import type * as requirementExtractionRuns from "../requirementExtractionRuns.js";
import type * as seed from "../seed.js";
import type * as seedWorkflows from "../seedWorkflows.js";
import type * as slack from "../slack.js";
import type * as slackLifecycle from "../slackLifecycle.js";
import type * as slackOnboarding from "../slackOnboarding.js";
import type * as slackOutbound from "../slackOutbound.js";
import type * as slackPresentation from "../slackPresentation.js";
import type * as sourceNodes from "../sourceNodes.js";
import type * as sourceSpans from "../sourceSpans.js";
import type * as threadActionConfirmations from "../threadActionConfirmations.js";
import type * as threads from "../threads.js";
import type * as users from "../users.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  acordTaxonomyBackfillBatches: typeof acordTaxonomyBackfillBatches;
  "actions/agentResponseFeedback": typeof actions_agentResponseFeedback;
  "actions/archiveNonCoverageRequirements": typeof actions_archiveNonCoverageRequirements;
  "actions/backfillAcordTaxonomy": typeof actions_backfillAcordTaxonomy;
  "actions/backfillCarrierIdentity": typeof actions_backfillCarrierIdentity;
  "actions/backfillChunks": typeof actions_backfillChunks;
  "actions/backfillComplianceRequirementShape": typeof actions_backfillComplianceRequirementShape;
  "actions/backfillLinesOfBusiness": typeof actions_backfillLinesOfBusiness;
  "actions/cleanupLegacyLineOfBusinessFields": typeof actions_cleanupLegacyLineOfBusinessFields;
  "actions/clientFileNaming": typeof actions_clientFileNaming;
  "actions/compactThreadHistory": typeof actions_compactThreadHistory;
  "actions/companyInformationExtraction": typeof actions_companyInformationExtraction;
  "actions/complianceRequirements": typeof actions_complianceRequirements;
  "actions/complianceReview": typeof actions_complianceReview;
  "actions/connectedEmail": typeof actions_connectedEmail;
  "actions/connectedEmailScan": typeof actions_connectedEmailScan;
  "actions/createOutboundImessageGroup": typeof actions_createOutboundImessageGroup;
  "actions/emailDraftReview": typeof actions_emailDraftReview;
  "actions/emailDrafts": typeof actions_emailDrafts;
  "actions/enrichCarrierIdentity": typeof actions_enrichCarrierIdentity;
  "actions/extractCompanyInfo": typeof actions_extractCompanyInfo;
  "actions/extractFromUpload": typeof actions_extractFromUpload;
  "actions/extractSupplementary": typeof actions_extractSupplementary;
  "actions/extractionIntegrityAudit": typeof actions_extractionIntegrityAudit;
  "actions/extractionReviews": typeof actions_extractionReviews;
  "actions/generateCoi": typeof actions_generateCoi;
  "actions/handleInboundEmail": typeof actions_handleInboundEmail;
  "actions/handleInboundImessage": typeof actions_handleInboundImessage;
  "actions/handleInboundOperatorImessage": typeof actions_handleInboundOperatorImessage;
  "actions/handleInboundSlack": typeof actions_handleInboundSlack;
  "actions/mailboxCoordinator": typeof actions_mailboxCoordinator;
  "actions/mcpChat": typeof actions_mcpChat;
  "actions/mirrorWebChatToImessage": typeof actions_mirrorWebChatToImessage;
  "actions/operatorAgentRichTools": typeof actions_operatorAgentRichTools;
  "actions/ownComplianceMonitor": typeof actions_ownComplianceMonitor;
  "actions/policyExtraction": typeof actions_policyExtraction;
  "actions/processThreadChat": typeof actions_processThreadChat;
  "actions/procurementIntake": typeof actions_procurementIntake;
  "actions/procurementPacketUpdate": typeof actions_procurementPacketUpdate;
  "actions/proposalExtraction": typeof actions_proposalExtraction;
  "actions/proposalReview": typeof actions_proposalReview;
  "actions/publicDemoAgent": typeof actions_publicDemoAgent;
  "actions/reExtractFromFile": typeof actions_reExtractFromFile;
  "actions/rechunkPolicy": typeof actions_rechunkPolicy;
  "actions/reconcilePolicy": typeof actions_reconcilePolicy;
  "actions/renderEmailPreview": typeof actions_renderEmailPreview;
  "actions/retryExtraction": typeof actions_retryExtraction;
  "actions/sendCertificateWorkflowJob": typeof actions_sendCertificateWorkflowJob;
  "actions/sendIntroImessage": typeof actions_sendIntroImessage;
  "actions/sendNotificationEmail": typeof actions_sendNotificationEmail;
  "actions/sendNotificationImessage": typeof actions_sendNotificationImessage;
  "actions/sendNotificationSlack": typeof actions_sendNotificationSlack;
  "actions/sendOperatorSlack": typeof actions_sendOperatorSlack;
  "actions/sendPendingEmail": typeof actions_sendPendingEmail;
  "actions/sendSlack": typeof actions_sendSlack;
  "actions/slackCredentials": typeof actions_slackCredentials;
  "actions/slackOAuth": typeof actions_slackOAuth;
  "actions/slackPresentation": typeof actions_slackPresentation;
  "actions/slackReconciliation": typeof actions_slackReconciliation;
  "actions/threadTitle": typeof actions_threadTitle;
  "actions/updateDocumentChunk": typeof actions_updateDocumentChunk;
  "actions/vendorComplianceMonitor": typeof actions_vendorComplianceMonitor;
  agentChannels: typeof agentChannels;
  agentHistory: typeof agentHistory;
  agentResponseFeedback: typeof agentResponseFeedback;
  agentTargets: typeof agentTargets;
  appCardLinks: typeof appCardLinks;
  auth: typeof auth;
  backfillDeclarationFacts: typeof backfillDeclarationFacts;
  backfillLinesOfBusinessBatches: typeof backfillLinesOfBusinessBatches;
  brokerProfiles: typeof brokerProfiles;
  carrierIdentityBackfill: typeof carrierIdentityBackfill;
  carrierIdentityCache: typeof carrierIdentityCache;
  certificateHolders: typeof certificateHolders;
  certificateLifecycle: typeof certificateLifecycle;
  certificateWorkflowJobs: typeof certificateWorkflowJobs;
  certificateWorkflowSettings: typeof certificateWorkflowSettings;
  certificates: typeof certificates;
  clRouterOperations: typeof clRouterOperations;
  cleanupLegacyLineOfBusinessFieldsBatches: typeof cleanupLegacyLineOfBusinessFieldsBatches;
  clientFiles: typeof clientFiles;
  clientProcurementRequests: typeof clientProcurementRequests;
  companyInformation: typeof companyInformation;
  compliance: typeof compliance;
  connectedEmail: typeof connectedEmail;
  connectedEmailAutomation: typeof connectedEmailAutomation;
  connectedOrgs: typeof connectedOrgs;
  conversationTurns: typeof conversationTurns;
  crons: typeof crons;
  declarationFacts: typeof declarationFacts;
  devClear: typeof devClear;
  documentChunks: typeof documentChunks;
  emailDeliveryAttempts: typeof emailDeliveryAttempts;
  emailDraftReviewLinks: typeof emailDraftReviewLinks;
  externalExtractionPayload: typeof externalExtractionPayload;
  extractionIntegrityAudit: typeof extractionIntegrityAudit;
  extractionReviews: typeof extractionReviews;
  extractionTraces: typeof extractionTraces;
  http: typeof http;
  imessageChats: typeof imessageChats;
  imessageInboundEvents: typeof imessageInboundEvents;
  imessageOutboundGroups: typeof imessageOutboundGroups;
  imessageOutboundSends: typeof imessageOutboundSends;
  imessagePrivacy: typeof imessagePrivacy;
  "lib/access": typeof lib_access;
  "lib/acordForms/select": typeof lib_acordForms_select;
  "lib/acordForms/types": typeof lib_acordForms_types;
  "lib/acordTaxonomyBackfill": typeof lib_acordTaxonomyBackfill;
  "lib/acordTaxonomyBackfillReport": typeof lib_acordTaxonomyBackfillReport;
  "lib/actionConfirmationFingerprint": typeof lib_actionConfirmationFingerprint;
  "lib/actionFailures": typeof lib_actionFailures;
  "lib/actorRef": typeof lib_actorRef;
  "lib/agentAttachmentContext": typeof lib_agentAttachmentContext;
  "lib/agentAttachmentLimits": typeof lib_agentAttachmentLimits;
  "lib/agentHistoryLoader": typeof lib_agentHistoryLoader;
  "lib/agentMessageHistory": typeof lib_agentMessageHistory;
  "lib/agentPolicyFocus": typeof lib_agentPolicyFocus;
  "lib/agentPolicyPresentation": typeof lib_agentPolicyPresentation;
  "lib/agentPrompts": typeof lib_agentPrompts;
  "lib/agentScope": typeof lib_agentScope;
  "lib/agentSteps": typeof lib_agentSteps;
  "lib/agentThreadAttachment": typeof lib_agentThreadAttachment;
  "lib/agentToolAudit": typeof lib_agentToolAudit;
  "lib/agentToolExecutors": typeof lib_agentToolExecutors;
  "lib/aiClassifier": typeof lib_aiClassifier;
  "lib/aiUtils": typeof lib_aiUtils;
  "lib/apiAuth": typeof lib_apiAuth;
  "lib/apiDto": typeof lib_apiDto;
  "lib/apiError": typeof lib_apiError;
  "lib/brandIcon": typeof lib_brandIcon;
  "lib/branding": typeof lib_branding;
  "lib/carrierIdentity": typeof lib_carrierIdentity;
  "lib/carrierIdentityBackfill": typeof lib_carrierIdentityBackfill;
  "lib/carrierIdentityEnrichment": typeof lib_carrierIdentityEnrichment;
  "lib/carrierIdentityProjection": typeof lib_carrierIdentityProjection;
  "lib/carrierIdentitySource": typeof lib_carrierIdentitySource;
  "lib/certificateBrokerEmail": typeof lib_certificateBrokerEmail;
  "lib/certificateDescription": typeof lib_certificateDescription;
  "lib/certificateEndorsements": typeof lib_certificateEndorsements;
  "lib/certificateHolderPopulation": typeof lib_certificateHolderPopulation;
  "lib/certificateHolderResolution": typeof lib_certificateHolderResolution;
  "lib/certificateIdentity": typeof lib_certificateIdentity;
  "lib/certificateRequestGate": typeof lib_certificateRequestGate;
  "lib/certificateRequirementPlan": typeof lib_certificateRequirementPlan;
  "lib/channelAgentRunner": typeof lib_channelAgentRunner;
  "lib/chatTools": typeof lib_chatTools;
  "lib/clRouterClient": typeof lib_clRouterClient;
  "lib/clRouterLanguageModel": typeof lib_clRouterLanguageModel;
  "lib/clientFileNames": typeof lib_clientFileNames;
  "lib/clientFiles": typeof lib_clientFiles;
  "lib/coiAttachmentGuards": typeof lib_coiAttachmentGuards;
  "lib/coiGenerator": typeof lib_coiGenerator;
  "lib/companyInformationExtraction": typeof lib_companyInformationExtraction;
  "lib/complianceAgent": typeof lib_complianceAgent;
  "lib/complianceCheck": typeof lib_complianceCheck;
  "lib/complianceRequirementMigration": typeof lib_complianceRequirementMigration;
  "lib/complianceTypes": typeof lib_complianceTypes;
  "lib/confidence": typeof lib_confidence;
  "lib/coverageBreakdown": typeof lib_coverageBreakdown;
  "lib/coverageNames": typeof lib_coverageNames;
  "lib/coverageScoping": typeof lib_coverageScoping;
  "lib/declarationFacts": typeof lib_declarationFacts;
  "lib/deletePolicyRowsInBatches": typeof lib_deletePolicyRowsInBatches;
  "lib/documentMapping": typeof lib_documentMapping;
  "lib/domains": typeof lib_domains;
  "lib/emailAddress": typeof lib_emailAddress;
  "lib/emailCancelIntent": typeof lib_emailCancelIntent;
  "lib/emailChange": typeof lib_emailChange;
  "lib/emailCommandExecutor": typeof lib_emailCommandExecutor;
  "lib/emailDelivery": typeof lib_emailDelivery;
  "lib/emailDraftArtifacts": typeof lib_emailDraftArtifacts;
  "lib/emailDraftService": typeof lib_emailDraftService;
  "lib/emailDraftSummary": typeof lib_emailDraftSummary;
  "lib/emailIdentity": typeof lib_emailIdentity;
  "lib/emailPayloadFields": typeof lib_emailPayloadFields;
  "lib/emailPolicySources": typeof lib_emailPolicySources;
  "lib/emailSendIntent": typeof lib_emailSendIntent;
  "lib/emailSubagent": typeof lib_emailSubagent;
  "lib/emailTemplate": typeof lib_emailTemplate;
  "lib/emailWorkflow": typeof lib_emailWorkflow;
  "lib/entityTypes": typeof lib_entityTypes;
  "lib/extraction": typeof lib_extraction;
  "lib/extractionFieldReview": typeof lib_extractionFieldReview;
  "lib/extractionIntegrityAudit": typeof lib_extractionIntegrityAudit;
  "lib/extractionPostProcess": typeof lib_extractionPostProcess;
  "lib/extractionPromotion": typeof lib_extractionPromotion;
  "lib/extractionPromptGuidance": typeof lib_extractionPromptGuidance;
  "lib/extractionTraceRouterFields": typeof lib_extractionTraceRouterFields;
  "lib/featureFlags": typeof lib_featureFlags;
  "lib/fireworksStructuredOutput": typeof lib_fireworksStructuredOutput;
  "lib/forwardReplyDirection": typeof lib_forwardReplyDirection;
  "lib/imapDestination": typeof lib_imapDestination;
  "lib/imapMailbox": typeof lib_imapMailbox;
  "lib/imessageAgentContext": typeof lib_imessageAgentContext;
  "lib/imessageAgentRunState": typeof lib_imessageAgentRunState;
  "lib/imessageAppCards": typeof lib_imessageAppCards;
  "lib/imessageConfig": typeof lib_imessageConfig;
  "lib/imessageDeterministicControls": typeof lib_imessageDeterministicControls;
  "lib/imessageGroupResolution": typeof lib_imessageGroupResolution;
  "lib/imessageIngress": typeof lib_imessageIngress;
  "lib/imessageOutbound": typeof lib_imessageOutbound;
  "lib/imessageSlashCommands": typeof lib_imessageSlashCommands;
  "lib/inboundEmailDeterministicControls": typeof lib_inboundEmailDeterministicControls;
  "lib/inboundEmailParser": typeof lib_inboundEmailParser;
  "lib/industries": typeof lib_industries;
  "lib/linesOfBusiness": typeof lib_linesOfBusiness;
  "lib/liteparsePreprocessor": typeof lib_liteparsePreprocessor;
  "lib/localSeedData": typeof lib_localSeedData;
  "lib/magicLinkTokens": typeof lib_magicLinkTokens;
  "lib/mailboxAutomation": typeof lib_mailboxAutomation;
  "lib/mapboxAddress": typeof lib_mapboxAddress;
  "lib/mcpAgentToolAccess": typeof lib_mcpAgentToolAccess;
  "lib/mcpProtocol": typeof lib_mcpProtocol;
  "lib/mergePdfs": typeof lib_mergePdfs;
  "lib/modelCatalog": typeof lib_modelCatalog;
  "lib/models": typeof lib_models;
  "lib/notificationEmailTemplate": typeof lib_notificationEmailTemplate;
  "lib/notificationThreadContext": typeof lib_notificationThreadContext;
  "lib/notificationTypes": typeof lib_notificationTypes;
  "lib/notify": typeof lib_notify;
  "lib/operatorAgentChannel": typeof lib_operatorAgentChannel;
  "lib/operatorAgentConfirmationPreflight": typeof lib_operatorAgentConfirmationPreflight;
  "lib/operatorAgentContinuation": typeof lib_operatorAgentContinuation;
  "lib/operatorAgentIntentRegistry": typeof lib_operatorAgentIntentRegistry;
  "lib/operatorAgentToolRegistry": typeof lib_operatorAgentToolRegistry;
  "lib/operatorIdentity": typeof lib_operatorIdentity;
  "lib/operatorMcpAttachments": typeof lib_operatorMcpAttachments;
  "lib/operatorMcpToolCatalog": typeof lib_operatorMcpToolCatalog;
  "lib/operatorSlackConfig": typeof lib_operatorSlackConfig;
  "lib/orgBranding": typeof lib_orgBranding;
  "lib/orgProfileFacts": typeof lib_orgProfileFacts;
  "lib/orgWiki": typeof lib_orgWiki;
  "lib/orgWikiExtraction": typeof lib_orgWikiExtraction;
  "lib/orgWikiPolicy": typeof lib_orgWikiPolicy;
  "lib/pdfFiller": typeof lib_pdfFiller;
  "lib/pdfSourceSpans": typeof lib_pdfSourceSpans;
  "lib/pipelineMutations": typeof lib_pipelineMutations;
  "lib/policyDocumentGate": typeof lib_policyDocumentGate;
  "lib/policyDocumentStructure": typeof lib_policyDocumentStructure;
  "lib/policyLookup": typeof lib_policyLookup;
  "lib/policyPartyContext": typeof lib_policyPartyContext;
  "lib/policyPeriodExtraction": typeof lib_policyPeriodExtraction;
  "lib/policyProductIdentity": typeof lib_policyProductIdentity;
  "lib/policyToolResolution": typeof lib_policyToolResolution;
  "lib/policyTypes": typeof lib_policyTypes;
  "lib/policyVersioning": typeof lib_policyVersioning;
  "lib/procurement": typeof lib_procurement;
  "lib/procurementCapabilities": typeof lib_procurementCapabilities;
  "lib/procurementIntake": typeof lib_procurementIntake;
  "lib/procurementNarrative": typeof lib_procurementNarrative;
  "lib/procurementPacket": typeof lib_procurementPacket;
  "lib/procurementRequirements": typeof lib_procurementRequirements;
  "lib/proposalMarkdown": typeof lib_proposalMarkdown;
  "lib/proposalReview": typeof lib_proposalReview;
  "lib/publicDemoAgent": typeof lib_publicDemoAgent;
  "lib/quoWebhook": typeof lib_quoWebhook;
  "lib/requirementAttachmentIntent": typeof lib_requirementAttachmentIntent;
  "lib/resend": typeof lib_resend;
  "lib/sdkCallbacks": typeof lib_sdkCallbacks;
  "lib/searchTokenizer": typeof lib_searchTokenizer;
  "lib/security": typeof lib_security;
  "lib/slackAvailability": typeof lib_slackAvailability;
  "lib/slackBlocks": typeof lib_slackBlocks;
  "lib/slackChannelRouting": typeof lib_slackChannelRouting;
  "lib/slackConfig": typeof lib_slackConfig;
  "lib/slackCredentials": typeof lib_slackCredentials;
  "lib/slackInteractions": typeof lib_slackInteractions;
  "lib/slackOAuthPolicy": typeof lib_slackOAuthPolicy;
  "lib/slackPayload": typeof lib_slackPayload;
  "lib/slackRetry": typeof lib_slackRetry;
  "lib/slackSecurity": typeof lib_slackSecurity;
  "lib/slackThreadContext": typeof lib_slackThreadContext;
  "lib/slackThreadTitle": typeof lib_slackThreadTitle;
  "lib/sourceTree": typeof lib_sourceTree;
  "lib/spreadsheetText": typeof lib_spreadsheetText;
  "lib/storedAgentFile": typeof lib_storedAgentFile;
  "lib/taskControlIntent": typeof lib_taskControlIntent;
  "lib/textChannelCommands": typeof lib_textChannelCommands;
  "lib/textChannelControls": typeof lib_textChannelControls;
  "lib/threadAccess": typeof lib_threadAccess;
  "lib/threadActionConfirmationValidators": typeof lib_threadActionConfirmationValidators;
  "lib/threadMessageValidators": typeof lib_threadMessageValidators;
  "lib/transportRenderers": typeof lib_transportRenderers;
  "lib/userFacingErrors": typeof lib_userFacingErrors;
  "lib/userPhone": typeof lib_userPhone;
  "lib/valueNormalization": typeof lib_valueNormalization;
  "lib/vendorComplianceTools": typeof lib_vendorComplianceTools;
  "lib/webChatDeterministicControls": typeof lib_webChatDeterministicControls;
  "lib/webRetrieval": typeof lib_webRetrieval;
  "lib/websiteBrand": typeof lib_websiteBrand;
  "lib/workflows/certificateRequest": typeof lib_workflows_certificateRequest;
  "lib/workflows/comms": typeof lib_workflows_comms;
  "lib/workflows/index": typeof lib_workflows_index;
  "lib/workflows/mailboxTasks": typeof lib_workflows_mailboxTasks;
  "lib/workflows/types": typeof lib_workflows_types;
  memoryMaintenance: typeof memoryMaintenance;
  migrations: typeof migrations;
  modelConfig: typeof modelConfig;
  modelRoutingEvents: typeof modelRoutingEvents;
  modelSettings: typeof modelSettings;
  notificationPreferences: typeof notificationPreferences;
  notificationSlack: typeof notificationSlack;
  notifications: typeof notifications;
  oauth: typeof oauth;
  operator: typeof operator;
  operatorAgent: typeof operatorAgent;
  operatorAgentRunner: typeof operatorAgentRunner;
  operatorImessage: typeof operatorImessage;
  operatorProvisioning: typeof operatorProvisioning;
  operatorSlack: typeof operatorSlack;
  orgWiki: typeof orgWiki;
  organizations: typeof organizations;
  orgs: typeof orgs;
  pendingEmails: typeof pendingEmails;
  policies: typeof policies;
  policyAuditLog: typeof policyAuditLog;
  policyFiles: typeof policyFiles;
  policyVersions: typeof policyVersions;
  presence: typeof presence;
  procurementMigration: typeof procurementMigration;
  procurementPacket: typeof procurementPacket;
  procurementProposals: typeof procurementProposals;
  procurementRequests: typeof procurementRequests;
  procurementRequirements: typeof procurementRequirements;
  procurementSms: typeof procurementSms;
  proposalExtraction: typeof proposalExtraction;
  proposalSourceNodes: typeof proposalSourceNodes;
  proposalSourceSpans: typeof proposalSourceSpans;
  publicDemo: typeof publicDemo;
  quoBrokerWebhook: typeof quoBrokerWebhook;
  rateLimits: typeof rateLimits;
  requirementExtractionRuns: typeof requirementExtractionRuns;
  seed: typeof seed;
  seedWorkflows: typeof seedWorkflows;
  slack: typeof slack;
  slackLifecycle: typeof slackLifecycle;
  slackOnboarding: typeof slackOnboarding;
  slackOutbound: typeof slackOutbound;
  slackPresentation: typeof slackPresentation;
  sourceNodes: typeof sourceNodes;
  sourceSpans: typeof sourceSpans;
  threadActionConfirmations: typeof threadActionConfirmations;
  threads: typeof threads;
  users: typeof users;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {
  migrations: import("@convex-dev/migrations/_generated/component.js").ComponentApi<"migrations">;
};
