import {
  Globe,
  Building2,
  Users,
  Mail,
  Paperclip,
  Shield,
  ClipboardCheck,
  MessagesSquare,
  NotebookPen,
  FileText,
  ClipboardList,
  FileCheck2,
  Link2,
  ScanText,
  MapPin,
  Activity,
  Send,
  Settings2,
  Archive,
  Trash2,
  Wrench,
} from "lucide-react";

import type { OperatorAgentToolName } from "@/convex/lib/operatorAgentToolRegistry";

export const toolActivityCategories = {
  web: { label: "Public research", icon: Globe },
  organizations: { label: "Organizations", icon: Building2 },
  brokers: { label: "Insurance providers", icon: Users },
  email: { label: "Email", icon: Mail },
  files: { label: "Files and attachments", icon: Paperclip },
  policies: { label: "Policies and coverage", icon: Shield },
  compliance: { label: "Compliance and certificates", icon: ClipboardCheck },
  conversations: { label: "Conversations", icon: MessagesSquare },
  notes: { label: "Company notes", icon: NotebookPen },
  packets: { label: "Procurement packets", icon: FileText },
  requests: { label: "Procurement requests", icon: ClipboardList },
  proposals: { label: "Proposals and reviews", icon: FileCheck2 },
  links: { label: "Sharing and access", icon: Link2 },
  extraction: { label: "Extraction", icon: ScanText },
  location: { label: "Addresses", icon: MapPin },
  health: { label: "Platform health", icon: Activity },
  send: { label: "Outbound messages", icon: Send },
  settings: { label: "Configuration", icon: Settings2 },
  archive: { label: "Archive", icon: Archive },
  delete: { label: "Deletion", icon: Trash2 },
} as const;

const operatorToolCategories = {
  list_mcp_tools: "settings",
  call_mcp_tool: "settings",
  web_search: "web",
  research_client: "web",
  research_broker: "web",
  search_organizations: "organizations",
  get_organization: "organizations",
  create_client_organization: "organizations",
  invite_operator: "settings",
  update_organization_profile: "organizations",
  set_organization_status: "organizations",
  get_broker_network_profile: "brokers",
  list_broker_network_profiles: "brokers",
  create_broker_network_profile: "brokers",
  update_broker_network_profile: "brokers",
  create_procurement_broker_outreach: "brokers",
  update_procurement_broker_outreach: "brokers",
  list_company_mailboxes: "email",
  search_company_email: "email",
  read_company_email_thread: "email",
  scan_workspace_mailbox: "email",
  get_procurement_forwarding_address: "email",
  list_procurement_email_threads: "email",
  get_procurement_email_thread: "email",
  preview_procurement_email_reconciliation: "email",
  update_procurement_email_thread: "email",
  file_procurement_email_quote: "email",
  get_company_email_attachment: "files",
  read_thread_attachment: "files",
  list_client_files: "files",
  read_client_file: "files",
  attach_client_file: "files",
  add_client_file: "files",
  update_client_file: "files",
  create_procurement_file_item: "files",
  update_procurement_file_item: "files",
  list_policies: "policies",
  lookup_policy: "policies",
  compare_coverages: "policies",
  lookup_policy_section: "policies",
  attach_policy_document: "policies",
  confirm_policy_fact: "policies",
  get_policy_status: "policies",
  import_policy_files: "policies",
  lookup_compliance_requirements: "compliance",
  generate_coi: "compliance",
  search_thread_history: "conversations",
  list_operator_conversations: "conversations",
  read_operator_conversation: "conversations",
  lookup_client_wiki: "notes",
  update_client_wiki: "notes",
  lookup_procurement_packet: "packets",
  preview_broker_packet: "packets",
  update_procurement_packet: "packets",
  list_procurement_requests: "requests",
  get_procurement_request: "requests",
  create_procurement_request: "requests",
  update_procurement_request: "requests",
  list_procurement_proposals: "proposals",
  get_procurement_proposal: "proposals",
  file_procurement_proposal: "proposals",
  generate_procurement_proposal_review: "proposals",
  confirm_procurement_proposal_review: "proposals",
  select_procurement_proposal: "proposals",
  list_broker_packet_links: "links",
  create_broker_packet_link: "links",
  rotate_broker_packet_link: "links",
  revoke_broker_packet_link: "links",
  list_extraction_issues: "extraction",
  retry_failed_policy_extraction: "extraction",
  retry_procurement_proposal_extraction: "extraction",
  cancel_procurement_proposal_extraction: "extraction",
  lookup_address: "location",
  get_operator_overview: "health",
  get_routing_status: "health",
  get_channel_health: "health",
  send_operator_slack_message: "send",
  set_client_feature_flag: "settings",
  archive_procurement_proposal: "archive",
  clear_all_agent_memory: "delete",
} satisfies Record<OperatorAgentToolName, keyof typeof toolActivityCategories>;

const clientToolCategories: Record<
  string,
  keyof typeof toolActivityCategories
> = {
  draft_email: "email",
  update_email_draft: "email",
  attach_policy_pdf_to_draft: "files",
  attach_file_to_draft: "files",
  attach_coi_to_draft: "compliance",
  list_email_drafts: "email",
  send_email_draft: "send",
  cancel_email_draft: "delete",
  expand_tools: "settings",
};

export function toolActivityIcon(name: string) {
  if (Object.hasOwn(clientToolCategories, name)) {
    return toolActivityCategories[clientToolCategories[name]].icon;
  }
  if (Object.hasOwn(operatorToolCategories, name)) {
    return toolActivityCategories[
      operatorToolCategories[name as OperatorAgentToolName]
    ].icon;
  }
  return Wrench;
}
